/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
Author: Taenshi (https://sketchfab.com/taenshi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abc-cube-toy-9443ba8835cf41fc8f89249aabf2e38b
Title: ABC Cube Toy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Toy(props) {
  const { nodes, materials } = useGLTF('/abc_cube_toy/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Green} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Green} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Green} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Green} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['Blue.001']} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Cube_color} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Green} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.Green} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Cube_color} />
    </group>
  )
}

useGLTF.preload('/abc_cube_toy/model.gltf')
